name: sukkur_prayer_timings
description: Sukkur Prayer Timings - Offline Islamic Namaz Timing App for Sukkur, Sindh
publish_to: 'none'
version: 1.1.7+26

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.1
  flutter_local_notifications: ^17.0.0
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  hijri: ^3.0.0
  timezone: ^0.9.4
  flutter_timezone: ^3.0.0
  share_plus: ^12.0.2
  path_provider: ^2.1.2
  geolocator: ^14.0.2
  flutter_qiblah: ^3.2.0
  url_launcher: ^6.3.0
  audioplayers: ^6.0.0
  package_info_plus: ^9.0.1
  home_widget: ^0.9.3
  workmanager: ^0.9.0+3
  http: ^1.6.0
  cached_network_image: ^3.4.1
  scrollable_positioned_list: ^0.3.8
  quran: ^1.2.9
  pdfx: ^2.5.0
  adhan: ^2.0.0+1
  geocoding: ^3.0.0
  lat_lng_to_timezone: ^0.2.0
  upgrader: ^13.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.3
  device_frame: ^1.1.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/favicon.png"
  web:
    generate: true
    image_path: "assets/favicon.png"
  windows:
    generate: true
    image_path: "assets/favicon.png"
  macos:
    generate: true
    image_path: "assets/favicon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/quran_pdfs/
    - assets/quran_translations/
    - assets/data/timings.json
    - assets/data/cities.txt
    - assets/images/
    - 'assets/azan_1.mp3'
    - 'assets/makkah_azan.mp3'
    - 'assets/azan_2.mp3'
    - 'assets/hayya_alas_salah.mp3'
    - 'assets/Jameel Noori Nastaleeq Kasheeda/'

  fonts:
    - family: SurahNames
      fonts:
        - asset: assets/fonts/surah_names.ttf
    - family: JameelNooriNastaleeqKasheeda
      fonts:
        - asset: 'assets/Jameel Noori Nastaleeq Kasheeda/Jameel Noori Nastaleeq Kasheeda.ttf'
