org.gradle.java.home=D:\\jbr
org.gradle.jvmargs=-Xmx2048M -XX:MaxMetaspaceSize=512M -XX:+UseSerialGC -Xss256k -XX:+HeapDumpOnOutOfMemoryError
org.gradle.workers.max=1
org.gradle.parallel=false
android.useAndroidX=true
android.enableJetifier=true
kotlin.incremental=false
kotlin.jvm.target.validation.mode=IGNORE
android.builtInKotlin=false
android.newDsl=false
